services:
  ### NGINX Server ########################################
  nginx:
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
      - ${CERTBOT_PATH}:/var/www/certbot
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
      - '${NGINX_HOST_HTTPS_PORT}:443'
    restart: unless-stopped
    networks:
      - frontend
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  ### API Service ####################################
  # api:
  #   build: .
  #   restart: unless-stopped
  #   working_dir: ${APP_CODE_PATH_CONTAINER}/api
  #   expose: [3334]
  #   command: /bin/sh -c "npm run dev"
  #   volumes:
  #     - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
  #     - ${APP_CODE_PATH_HOST}/api/openssl.cnf:/etc/ssl/openssl.cnf
  #   networks:
  #     - backend

  ### Web Service #########################################
  web:
    build:
      context: ./web
    ports:
      - '8080:8080'
    volumes:
      - ./web:/var/www/app/web
    stdin_open: true
    tty: true
    networks:
      - backend
    environment:
      - NODE_ENV=development

  ### MariaDB #############################################
  # mariadb:
  #   build:
  #     context: ./mariadb
  #     args:
  #       - MARIADB_VERSION=${MARIADB_VERSION}
  #   volumes:
  #     - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
  #     - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
  #   ports:
  #     - '${MARIADB_PORT}:3306'
  #   restart: unless-stopped
  #   environment:
  #     - TZ=${DEFAULT_TIMEZONE}
  #     - MYSQL_DATABASE=${MARIADB_DATABASE}
  #     - MYSQL_USER=${MARIADB_USER}
  #     - MYSQL_PASSWORD=${MARIADB_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  #   networks:
  #     - backend

  # cron:
  #   image: node:lts
  #   restart: unless-stopped
  #   working_dir: ${APP_CODE_PATH_CONTAINER}/api
  #   command: /bin/sh -c "node ace run:scheduler"
  #   volumes:
  #     - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
  #   networks:
  #     - backend
  #   depends_on:
  #     - api

  # phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - mariadb
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '9003:80'
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
  #     - './uploads.ini:/usr/local/etc/php/php.ini'
  #   networks:
  #     - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}
